"""Initial migrations

Revision ID: 06692f681f37
Revises: 74a580140581
Create Date: 2023-06-12 13:35:18.049335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06692f681f37'
down_revision = '74a580140581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
